repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.2
    hooks:
      - id: golangci-lint-full
        name: golangci-lint-full
        description: Fast linters runner for Go. Runs on all files in the repo.
        entry: golangci-lint run --fix
        language: golang
        require_serial: true
        pass_filenames: false