services:
  postgres:
    image: postgres:14
    container_name: "pg"
    ports:
      - "5432:5432"
    env_file: "../.env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
