name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Start Linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2

